### PR TITLE
Added support for the Password Flow authentication method.

### PR DESCRIPTION
**Pull request by DaveWoodCom**
Required adding support for url encoding parameters in ANRequest, and also to store the JSON error message into the error object in -sendRequestWithRepresentationCompletion

### CODE REVIEW

**Comment by beccadax** [comment]
Thanks very much for your patch, Dave. I've merged it into a [new password-auth branch](https://github.com/brentdax/appnetkit/tree/password-auth) and made a few changes:
1. I made a bunch of style changes to match the existing code.
2. I've made `passwordGrantSecret` an ANAuthenticator property, since you'll generally use the same secret every time you authenticate a user, and changed the signature of the password grant method to `-accessTokenForScopes:withUsername:password:completion:`.
3. We already have some code for doing form data encoding, so I switched to using that instead of the new code you wrote in `-[ANRequest body]`.

I don't have access to a password grant secret, so I can't test these changes. Can you pull the password-auth branch and let me know if everything still works on your end? You'll have to modify your code to set the new property and use the new method name, but it should be an easy integration.

If there aren't any problems, I'll merge this into master.

Thanks!

**Comment by DaveWoodCom** [comment]
Ok cool.  Have been offline for the last 4 days, and am now in catch up mode.  Will test this branch this week and get back to you.

**Comment by DaveWoodCom** [comment]
Works great!

Thanks.

**Comment by beccadax** [comment]
Great! I've merged the password-auth branch to master, which is good news since cherry-picking changes between the two branches has been a bit of a pain. Thanks for your work on this feature!

**Pull request closed without merging**
